name: My Beautiful Workflow

on:
  workflow_dispatch:
    inputs:
      foobar:
        description: "Test input"
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "${{ inputs.foobar }}"
