name: Test dispatch

on:
  workflow_dispatch:
    inputs:
      antrea-repository:
        description: 'The Antrea repository to check-out'
        required: false
        default: ''
      antrea-ref:
        description: 'The Git ref to use when checking-out the Antrea repository'
        required: false
        default: ''
      docker-tag:
        description: 'Tag for built Docker image'
        required: false
        default: ''

jobs:
  dispatch-test:
    runs-on: [ubuntu-latest]
    steps:
    - name: Run tests on ARM images
      if: ${{ env.DOCKER_TAG != 'latest' }}
      uses: benc-uk/workflow-dispatch@v1
      with:
        repo: vmware-tanzu/antrea-build-infra
        ref: refs/heads/main
        workflow: Build Antrea ARM images and push manifest
        token: ${{ secrets.WORKFLOW_DISPATCH_PAT }}
        inputs: ${{ toJSON(github.event.inputs) }}
