name: TestWindows

on:
  push:
    branches:
      - master

jobs:
  test3:
    runs-on: windows-2019
    steps:
      - name: Install
        shell: pwsh
        run: |
          Invoke-WebRequest -UseBasicParsing -Uri https://www.7-zip.org/a/7z2107-x64.exe -OutFile 7z2107-x64.exe
          cmd /c start /wait 7z2107-x64.exe /S
          del 7z2107-x64.exe;  $env:Path = $env:Path+';C:/Program Files/7-Zip'
          Invoke-WebRequest -UseBasicParsing -UserAgent "Wget" -Uri https://downloads.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z -OutFile mingw.7z
          ls
          7z x mingw.7z; cp c:/mingw64/bin/mingw32-make.exe c:/mingw64/bin/make.exe
