name: Build and push image

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: [windows-2019]
    steps:
    - uses: actions/checkout@v2
    - name: Push image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        TAG: ${{ github.ref }}
      run: |
        export VERSION="${TAG:10}"
        echo "$VERSION"
        echo "${TAG:10}"
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker pull golang
        docker tag golang antoninbas/test-go-windows:latest
        docker push antoninbas/test-go-windows:latest
      shell: bash
