name: Test2
on:
  release:
    types: [published]

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Echo
        run: |
          echo "on.release.types = [published]"
