name: Test1

on:
  push:
    tags:
      - v*

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Echo
        run: |
          echo "on.push.tags = [v*]"
