name: Upload assets to release

on:
  release:
    types:
      - created

jobs:
  get-version:
    runs-on: [ubuntu-latest]
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
    - name: Extract version from Github ref
      id: get-version
      env:
        TAG: ${{ github.ref }}
      run: |
        version=${TAG:10}
        echo "::set-output name=version::$version"

  # build:
  #   runs-on: [ubuntu-latest]
  #   needs: get-version
  #   steps:
  #   - name: Trigger Antrea arm builds and multi-arch manifest update
  #     uses: benc-uk/workflow-dispatch@v1
  #     with:
  #       repo: vmware-tanzu/antrea-build-infra
  #       ref: refs/heads/main
  #       workflow: Build Antrea ARM images and push manifest
  #       token: "aaaaaa"
  #       inputs: ${{ format('{{ "antrea-repository":"vmware-tanzu/antrea", "antrea-ref":"{0}", "docker-tag":"{1}" }}', github.ref, needs.get-version.outputs.version) }}

  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build assets
      run: |
        mkdir assets
        echo "1" > assets/test-1.txt
        echo "2" > assets/test-2.txt
    - name: Upload assets
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_paths: '["./assets/*"]'
