name: Upload assets to release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Get release id
      env:
        TAG: ${{ github.ref }}
      run: echo ::set-env name=GITHUB_UPLOAD_URL::$(curl -s https://api.github.com/repos/vmware-tanzu/antrea/releases/tags/${TAG:10} | jq '.upload_url')
    - name: Build project # This would actually build your project, using zip for an example artifact
      if: env.GITHUB_UPLOAD_URL != 'null'
      run: |
        zip --junk-paths my-artifact README.md
    - name: Upload Release Asset
      if: env.GITHUB_UPLOAD_URL != 'null'
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.GITHUB_UPLOAD_URL }}
        asset_path: ./my-artifact.zip
        asset_name: my-artifact.zip
        asset_content_type: application/zip
