name: Workflows
on:
  workflow_run:
    workflows: ["Check Python version"]
    types:
      - requested
jobs:
  show:
    name: Show
    runs-on: ubuntu-latest
    steps:
    - run : |
        echo "${{ toJSON(github.event.workflow) }}"
        echo "${{ toJSON(github.event.workflow_run) }}"
